--- 
tenants:
  - name: ACME
    mac_vrf_vni_base: 10000
    redistribute_mlag_ibgp_peering_vrfs: false
    vrfs:
      - name: VRF_A
        vrf_vni: 10
        svis:
          - id: 10 
            name: DMZ
            enabled: true
            ip_address_virtual: 10.1.10.1/24
          - id: 20
            name: Internal
            enabled: true
            ip_address_virtual: 10.1.20.1/24
        l3_interfaces:
          - interfaces: [Ethernet9]
            ip_addresses: [10.1.5.2/31]
            nodes: [leaf3]
            enabled: True
        bgp_peers:
          - ip_address: 10.1.5.3
            remote_as: 1
            nodes: [leaf3]