---
fabric_name: FABRIC

p2p_uplinks_mtu: 1550

bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

dns_domain: atd.lab
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 192.168.0.1


l3_edge:
  p2p_links_ip_pools:
    dci_evpn_gateway: 172.31.252.0/24
  p2p_links:
    - id: 1
      ip_pool: dci_evpn_gateway
      nodes: [borderleaf1, borderleaf2]
      interfaces: [Ethernet1, Ethernet1]
      as: [65190, 65290]
      include_in_underlay_protocol: true
    - id: 2
      ip_pool: dci_evpn_gateway
      nodes: [borderleaf1, borderleaf2]
      interfaces: [Ethernet2, Ethernet2]
      as: [65190, 65290]
      include_in_underlay_protocol: true