---
servers:
  - name: host1
    adapters: 
      - switch_ports: [Ethernet7, Ethernet7]
        switches: [leaf1, leaf2]
        vlans: 10
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: To host1
          mode: active
  - name: host3
    adapters: 
      - switch_ports: [Ethernet7, Ethernet7]
        switches: [leaf3, leaf4]
        vlans: 20
        mode: access
        spanning_tree_portfast: edge
        port_channel:
          description: To host3
          mode: active