---
- name: Deploy configs to CVP
  hosts: cvp
  tasks:
    - name: Provision CVP with AVD configs
      ansible.builtin.import_role:
        name: arista.avd.eos_config_deploy_cvp
      vars:
        container_root: 'FABRIC'
        configlets_prefix: 'AVD'
        state: present
        execute_tasks: true
        cv_collection: v3
